### ISSUE TITLE
Advice .gitignore

### ISSUE THREAD

**Issue by adrienbrunet** [Skarlso/myrpg#1]
If you carry on that project, (I'd love to see what a rpg on django would look like), add a .pyc in your .gitignore
It would be much easier to have a look into your project =)

Github provides good examples of .gitignore if you need one.

**Comment by Skarlso** [comment]
Ahh thanks for the spot man!
Yeah this is sort of a pet project to learn django and see how intuitive it is to work with. So I want to finish it. :-) 

Thanks for the tip. I'm going to do that.

**Comment by adrienbrunet** [comment]
I'll be glad to help if I can. I'll try to review the code from time to time =)

**Comment by Skarlso** [comment]
Thanks man!! That is VERY much appreciated. :)
